### ISSUE TITLE
Not able to use IDE find in file

### ISSUE THREAD

**Issue by alexvelea** [niftythoughts/ansi-highlighter-premium#4] opened 2022-10-21 11:53 UTC
Initially, I was using a sed command `sed 's/\x1B\[[0-9;]\{1,\}[A-Za-z]//g'` to remove colors from log files so I can search them. I really enjoy seeing them colored, but I'm not able to perform searches in them using the default search box in GoLand, in my case.

Would there be a way to make them searchable as well, not only to display them?

**Comment by niftythoughts** [comment] 2022-10-21 19:22
Hi, 
I am not able to reproduce the issue - tested with version 22.2.4, search works properly
<img width="1101" alt="Screen Shot 2022-10-21 at 9 12 47 PM" src="https://user-images.githubusercontent.com/104358007/197272387-d59c9267-008b-41a4-a2e2-eb4f25346a5d.png">

Please specify the following:
- your GoLand version
- ANSI Highlighter version
- the steps to reproduce the issue 
- the "non-searchable" file

**Comment by alexvelea** [comment] 2022-10-25 11:49
Sorry for being so vague. Realized afterward that I'm able to search text if it's one color.
We're using `github.com/sirupsen/logrus` for logging.
I wanted to search for errors in the file, honestly.
Unfortunately, they are displayed like `[E]` and the E is in a different color than the brackets.

![Screenshot 2022-10-25 at 14 44 17](https://user-images.githubusercontent.com/10797318/197764805-ed205f9a-c6d1-4ce4-98a9-0125df4e2626.png)

**Comment by niftythoughts** [comment] 2022-10-25 13:08
No problem, with regards to the E in different color it must be coming from Logrus highlighting style/configuration - the ANSI control codes sitting behind can be inspected by opening the log file in plain mode.

Closing the issue.

**Comment by niftythoughts** [comment] 2022-10-25 13:36
The issue is not irrelevant at second thought, support for search omitting ANSI codes should be added in the future.

Ticket re-opened as enhancement, thanks for reporting.

**Comment by alexvelea** [comment] 2022-10-25 13:38
Thank you for looking into this, and sorry again for the really bad reporting 🙏🏻

**Comment by niftythoughts** [comment] 2022-11-14 10:53
Issue resolved with [22.3.1-EAP](https://plugins.jetbrains.com/plugin/9707-ansi-highlighter-premium/versions/stable/250492)

22.3.1 should follow on time with IDE official release

**Comment by niftythoughts** [comment] 2022-11-25 09:07
[22.3.1](https://plugins.jetbrains.com/plugin/9707-ansi-highlighter-premium/versions/stable/257199) released.

**Closed as completed by niftythoughts** 2022-11-25 09:07 UTC
Labels: enhancement
